package com.sari.gamecorner.model;

public enum Genre {
    SHOOTER,
    SIMULATOR,
    ADVENTURE,
    ROLE_PLAYING_RPG,
    SPORT,
    STRATEGY,
    TURN_BASED_STRATEGY_TBS,
    TACTICAL,
    FIGHTING,
    HACK_AND_SLASH_PER_BEAT_EM_UP,
    REAL_TIME_STRATEGY_RTS,
    POINT_AND_CLICK,
    PUZZLE,
    RACING,
    PINBALL
}
